//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class BaseManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(BaseManager), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("OneFrame", get_OneFrame, set_OneFrame);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OneFrame(IntPtr L)
	{
		try
		{
			ToLua.PushSealed(L, BaseManager.OneFrame);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_OneFrame(IntPtr L)
	{
		try
		{
			UnityEngine.WaitForEndOfFrame arg0 = (UnityEngine.WaitForEndOfFrame)ToLua.CheckObject(L, 2, typeof(UnityEngine.WaitForEndOfFrame));
			BaseManager.OneFrame = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

